spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arvindve/springcloud-configfiles.git
server:
  port: 8888

